name: todolist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  confirm_dialog: ^1.0.1
  intl: ^0.18.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  flutter_hooks: ^0.18.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
